### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by BakhodirIsmatov** [zjnu-acm/judge#13]
Please tell me about instaliation! 
Thanks!!!!

**Comment by zhanhb** [comment]
For windows 7+/Windows server 2008+
1. install mariadb(mysql), mingw64(https://sourceforge.net/projects/mingw-w64/), jdk, tomcat
2. Add %MINGW_HOME%\bin to PATH
3. git clone https://github.com/zjnu-acm/judge
4. Modify password configuration([judge-site/src/main/resources/application-jdbc.properties](https://github.com/zjnu-acm/judge/blob/8c9b1d8cc0d8309f995ad379ec37012269f6f7e7/judge-site/src/main/resources/application-jdbc.properties)), schema will automatic created in step 6
5. cd judge && mvnw package
6. copy target/judge.war to tomcat/webapps and (re)start tomcat
7. Modify the configuration in table `language`
